
import type { Metadata } from "next";
import "./globals.scss";
import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Fluidsep Next App",
  description: "Generated by tnjensen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <div className="wrapper">
         <Header />
          <div>
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
